# Importing Libraries

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Dataset

In [18]:
dataset = pd.read_csv('YoutubeCommentsDataSet.csv', quoting = 3)

# Cleaning the Text

In [35]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 18408):
  comment = str(dataset['Comment'][i])  # Convert to string
  comment = re.sub('[^a-zA-Z]', ' ', comment)
  comment = comment.lower()
  comment = comment.split()
  ps = PorterStemmer()
  comment = [ps.stem(word) for word in comment if not word in set(stopwords.words('english'))]
  comment =' '.join(comment)
  corpus.append(comment)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [118]:
print(corpus)

['let forget appl pay requir brand new iphon order use signific portion appl user base wasnt abl use even want success iphon incorpor technolog older iphon replac number peopl could use technolog increas', 'nz retail even contactless credit card machin like paywav support appl pay like high fee come', 'forev acknowledg channel help lesson idea explan quit help youll sit comfort monitor account growth', 'whenev go place take appl pay happen often drag contactless covid habit get appl card gotten use appl pay get serious annoy store take feel like shock crazi quickli took shop routin offici brainwash appl feel inconveni even carri physic card pocket', 'appl pay conveni secur easi use use korean japanes airport need physic credit card', 'hound bank adopt appl pay understand want extra fee easi quick checkout', 'got appl pay south africa wide accept', 'need appl pay physic credit card', 'unit state abund retail accept appl pay still good carri physic card still larg quantiti place accept a

# Creating Bag of Words Model

In [168]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features = 5000)
X = tv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

len(X[0])

5000

# Splitting the dataset into Training and Test Set

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Training the Logistic Regression Model on the Training Set

In [170]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

# Predicting the Test Set Results

In [171]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[['positive' 'positive']
 ['neutral' 'neutral']
 ['neutral' 'neutral']
 ...
 ['neutral' 'negative']
 ['neutral' 'neutral']
 ['positive' 'positive']]


# Making the Confusion Matrix

In [172]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 168  158  170]
 [  56  560  293]
 [  23  180 2074]]


0.7609994568169474